napzakmarket/Napzak-BE

src/main/java/com/napzak/domain/store/api/controller/StoreController.java
- closes #4
최대 7개까지 등록 가능합니다. 
이 외 요청(빈 리스트, 중복 존재, 7개 초과, 존재하지 않는 장르)들에 대해서도 이전과 같이 잘 처리됩니다.
=> [feat] #4 - 최대 등록 가능 선호 장르 수 수정

src/main/java/com/napzak/domain/product/api/controller/ProductController.java, src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyDto.java, src/main/java/com/napzak/domain/product/api/dto/response/ProductSellDto.java
- closes #7
interestCount와 chatCount를 포함하여 반환합니다
최대 6개의 데이터를 반환합니다.
=> [feat] #7 - 홈화면 인기 팔아요, 구해요 dto와 반환 데이터 수 수정

src/main/java/com/napzak/domain/store/api/controller/StoreController.java, src/main/java/com/napzak/domain/store/api/dto/response/StoreInfoResponse.java
- closes #13
내 상점 여부를 함께 반환합니다.
=> [feat] #13 - 상점 정보 조회 시 isStoreOwner를 함께 반환하도록 수정

src/main/java/com/napzak/domain/external/core/entity/enums/LinkType.java, src/main/java/com/napzak/domain/store/api/controller/StoreController.java, src/main/java/com/napzak/domain/store/api/dto/response/OnboardingTermsListResponse.java, src/main/java/com/napzak/domain/store/api/dto/response/SettingLinkResponse.java, src/main/java/com/napzak/domain/store/api/dto/response/TermsDto.java, src/main/java/com/napzak/domain/store/api/exception/StoreSuccessCode.java, src/main/java/com/napzak/global/common/config/SecurityConfig.java
- closes #17
온보딩 때 조회될 이용약관, 개인정보처리방침 관련 정보를 반환합니다.
=> [feat] #17 - 온보딩 서비스 이용약관 정보 조회 API 구현

src/main/java/com/napzak/domain/product/api/controller/ProductApi.java, src/main/java/com/napzak/domain/product/api/controller/ProductController.java, src/main/java/com/napzak/domain/product/api/dto/request/TradeStatusRequest.java, src/main/java/com/napzak/domain/product/api/exception/ProductErrorCode.java, src/main/java/com/napzak/domain/product/api/exception/ProductSuccessCode.java, src/main/java/com/napzak/domain/product/api/service/ProductService.java, src/main/java/com/napzak/domain/product/core/ProductRepository.java, src/main/java/com/napzak/domain/product/core/ProductUpdater.java, src/main/java/com/napzak/domain/product/core/entity/enums/TradeStatus.java
- closes #20
상품 상태 변경 api를 구현하였습니다
=> [feat] #20 - 상품 상태 변경 api 구현

src/main/java/com/napzak/domain/genre/core/GenreRepository.java, src/main/java/com/napzak/domain/genre/core/GenreRetriever.java, src/main/java/com/napzak/domain/product/api/ProductGenreFacade.java, src/main/java/com/napzak/domain/product/api/controller/ProductController.java, src/main/java/com/napzak/domain/product/api/dto/response/RecommendGenreDto.java, src/main/java/com/napzak/domain/product/api/dto/response/RecommendResponse.java, src/main/java/com/napzak/domain/product/api/dto/response/RecommendSearchWordDto.java, src/main/java/com/napzak/domain/product/api/exception/ProductSuccessCode.java, src/main/java/com/napzak/domain/product/api/service/ProductService.java, src/main/java/com/napzak/domain/product/core/SearchWordRepository.java, src/main/java/com/napzak/domain/product/core/SearchWordRetriever.java, src/main/java/com/napzak/domain/store/api/StoreGenreFacade.java
- closes #24
추천 검색어와 추천 장르를 조회합니다. 
추천 장르는 recommend order 오름차순 반환합니다. 
데이터가 존재하지 않으면 오류가 아닌 빈 리스트 반환합니다.
=> [feat] #24 - 추천 검색어, 추천 장르 조회 api 구현

src/main/java/com/napzak/domain/product/api/controller/ProductController.java, src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyListResponse.java, src/main/java/com/napzak/domain/product/api/dto/response/ProductSellListResponse.java, src/main/java/com/napzak/domain/product/api/service/ProductService.java, src/main/java/com/napzak/domain/product/core/ProductRepositoryCustom.java, src/main/java/com/napzak/domain/product/core/ProductRepositoryCustomImpl.java, src/main/java/com/napzak/domain/product/core/ProductRetriever.java
- closes #31 
- 상품 리스트 조회 시 총 상품 개수 포함
- 상품 리스트 판매중-예약중-판매완료 순으로 정렬
- productCount 포함
- 판매중-예약중-판매완료 순으로 정렬
- productCount 포함
- 판매중-예약중-판매완료 순으로 정렬
- productCount 포함
- 판매중-예약중-판매완료 순으로 정렬
- productCount 포함
- 판매중-예약중-판매완료 순으로 정렬
- productCount 포함
- 판매중-예약중-판매완료 순으로 정렬
- productCount 포함
- 판매중-예약중-판매완료 순으로 정렬
=> [feat] #31 - 상품 리스트 조회 관련 수정

src/main/java/com/napzak/domain/product/api/controller/ProductController.java, src/main/java/com/napzak/domain/product/api/dto/request/ProductReportRequest.java, src/main/java/com/napzak/domain/product/api/dto/response/ProductReportResponse.java, src/main/java/com/napzak/domain/product/api/exception/ProductSuccessCode.java, src/main/java/com/napzak/domain/product/api/service/ProductService.java, src/main/java/com/napzak/domain/product/core/ProductReportRepository.java, src/main/java/com/napzak/domain/product/core/ProductReportSaver.java, src/main/java/com/napzak/domain/product/core/entity/ProductReportEntity.java, src/main/java/com/napzak/domain/store/api/controller/StoreController.java, src/main/java/com/napzak/domain/store/api/dto/request/StoreReportRequest.java, src/main/java/com/napzak/domain/store/api/dto/request/StoreWithdrawRequest.java, src/main/java/com/napzak/domain/store/api/dto/response/StoreReportResponse.java, src/main/java/com/napzak/domain/store/api/dto/response/StoreWithdrawResponse.java, src/main/java/com/napzak/domain/store/api/exception/StoreSuccessCode.java, src/main/java/com/napzak/domain/store/api/service/StoreService.java, src/main/java/com/napzak/domain/store/core/StoreReportRepository.java, src/main/java/com/napzak/domain/store/core/StoreReportSaver.java, src/main/java/com/napzak/domain/store/core/StoreRetriever.java, src/main/java/com/napzak/domain/store/core/StoreUpdater.java, src/main/java/com/napzak/domain/store/core/WithdrawRepository.java, src/main/java/com/napzak/domain/store/core/WithdrawSaver.java, src/main/java/com/napzak/domain/store/core/entity/WithdrawEntity.java, src/main/java/com/napzak/domain/store/core/entity/WithdrawTableConstants.java, src/main/java/com/napzak/global/common/config/WebConfig.java, src/main/java/com/napzak/global/common/util/discord/DiscordWebhookProperties.java, src/main/java/com/napzak/global/common/util/discord/DiscordWebhookSender.java
- closes #37 
- 신고/탈퇴 관련 api 구현
- discord 연동
=> [feat] #37 - 신고/탈퇴 관련 api 구현

.github/workflows/dev-CD.yml, .github/workflows/prod-CD.yml
- closes #40 
github workflow에서의 경로를 수정
=> [deploy] #40 - github workflow 수정

docker-compose-dev.yml, docker-compose-prod.yml
- closes #42 
docker-compose 수정 - redis volume 추가
=> [deploy] #42 - docker-compose 수정

src/main/java/com/napzak/domain/product/api/controller/ProductApi.java, src/main/java/com/napzak/domain/store/api/controller/StoreApi.java, src/main/java/com/napzak/domain/store/api/service/StoreService.java, src/main/java/com/napzak/domain/store/core/StorePhotoRepository.java, src/main/java/com/napzak/domain/store/core/StorePhotoRetriever.java, src/main/java/com/napzak/domain/store/core/StoreUpdater.java, src/main/java/com/napzak/domain/store/core/entity/StorePhotoEntity.java
- closes #44 
-  회원가입 시 기본이미지 삽입 구현
- 누락된 swagger 문서화 추가
=> [feat] #44 - [feat] 회원가입 시 기본이미지 삽입 구현

src/main/java/com/napzak/domain/product/api/controller/ProductController.java
- closes #번호
팔아요, 구해요 상품 수정 method를 Put으로 변경하였습니다
=> [chore] #46 - 상품 수정 method put으로 변경

src/main/java/com/napzak/domain/product/core/ProductPhotoRemover.java, src/main/java/com/napzak/domain/product/core/ProductPhotoRepository.java, src/main/java/com/napzak/domain/product/core/ProductRemover.java
- closes #48 
해당 상품의 사진을 삭제하는 로직을 추가하지 않아 무결성 문제가 생기던 것을 해결하였습니다.
=> [fix] #48 - 상품 삭제 api 관련 사진도 함께 삭제

src/main/java/com/napzak/domain/store/api/controller/StoreApi.java, src/main/java/com/napzak/domain/store/api/controller/StoreController.java
- closes #51
모지.? 저번에 분명분명분~명 작업했던 기억이 있는데 흔적도 없이 사라져있어요.
=> [feat] #51 - 로그인 response에 refresh token 포함하여 반환

src/main/java/com/napzak/global/auth/jwt/filter/JwtAuthenticationFilter.java
=> [fix] #56 - jwt Auth filter에 ONBOARDING 관련 포함

src/main/java/com/napzak/domain/product/api/controller/ProductController.java, src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyModifyResponse.java, src/main/java/com/napzak/domain/product/api/dto/response/ProductSellModifyResponse.java
- closes #58
디스코드 스레드 요청에 따라 response에 genreId 필드를 추가하였습니다.
=> [feat] #58 - 상품 수정을 위한 정보 조회 api의 response에 genreId 추가

src/main/java/com/napzak/domain/store/api/controller/StoreController.java, src/main/java/com/napzak/domain/store/api/dto/request/RoleDto.java, src/main/java/com/napzak/domain/store/api/exception/StoreSuccessCode.java, src/main/java/com/napzak/domain/store/api/service/StoreService.java
- closes #67
클라이언트 요청으로 테스트 때 임시로 쓸 role 변경 api 구현하였습니다.
=> [feat] #67 - role 변경 api 구현

src/main/java/com/napzak/domain/store/core/entity/SlangRetriever.java, src/main/java/com/napzak/global/common/slang/SlangFilter.java
- closes #69 
닉네임 검증 오류 해결
- redis에 blank 삽입되지 않도록 필터링 조건 추가
- 비속어 일부 일치는 정상, 전체 일치가 포함될 경우에만 비속어로 필터링하도록 조건 변경
=> [fix] #69 - 닉네임 검증 오류 해결

src/main/java/com/napzak/domain/product/api/dto/response/ProductPhotoDto.java
- closes #71
클라이언트 요청으로 dto 필드명 변경합니다
=> [refactor] #71 - photoSequence -> sequence 필드명 변경

src/main/java/com/napzak/domain/product/core/ProductSaver.java, src/main/java/com/napzak/domain/product/core/entity/ProductEntity.java
=> [fix] #82 - saver에서 isVisible 필드를 명시적으로 true로 지정

src/main/java/com/napzak/domain/product/core/ProductRepositoryCustomImpl.java
- closes #84 
홈화면 인기상품 판매중만 노출되도록 ProductRepositoryCustomImpl에 필터링 조건을 추가했습니다.
AS-IS
예약중, 판매완료 상품도 찜 수 많을 경우 홈화면 인기상품에 노출됐습니다.
TO-BE
홈화면 인기상품에는 판매중 상품만 노출됩니다.
=> [#84] Feat(ProductRepositoryCustomImpl): 홈화면 인기상품 판매중만 노출되도록 필터링 조건 추가

common-module/src/main/java/com/napzak/common/config/FirebaseConfig.java
- closes #108 
📌 변경 내용
FirebaseConfig에서 Firebase Admin SDK 초기화 경로를 환경에 따라 다르게 처리하도록 수정
application-local.yml: classpath: 경로 사용 (src/main/resources/firebase/napzak-firebase-adminsdk.json)
application-dev.yml: file: 경로 사용 (/app/firebase/napzak-firebase-adminsdk.json)
✅ 주요 변경
firebase.config-path 설정값을 ResourceUtils.getFile()로 읽도록 통합
로컬/서버 양쪽 환경 모두에서 Firebase 초기화 가능하도록 대응
🧪 테스트
로컬에서 정상 동작 확인 (application-local.yml 기준)
컨테이너 환경에서는 외부 파일 경로로 Firebase 정상 초기화 확인 예정
=> [fix] #108 - FirebaseConfig 수정

Dockerfile-api-dev, Dockerfile-chat-dev
- closes #141 
openjdk:alpine 런타임 이미지에 tzdata 설치 추가
=> [fix] #143 - openjdk:alpine 런타임 이미지에 tzdata 설치 추가

.github/workflows/prod-api-CD.yml, .github/workflows/prod-chat-CD.yml
=> [fix] #180 - environment 수정

.github/workflows/prod-api-CD.yml, .github/workflows/prod-api-CI.yml, .github/workflows/prod-chat-CD.yml, .github/workflows/prod-chat-CI.yml
=> [deploy] #187 - CI/CD 파일 수정

.github/workflows/prod-api-CD.yml, .github/workflows/prod-api-CI.yml, .github/workflows/prod-chat-CI.yml, docker-compose-api-blue-prod.yml, docker-compose-api-green-prod.yml, docker-compose-api-prod.yml
=> [deploy] #194 - api 서버 무중단배포 환경 구축

.github/workflows/prod-chat-CD.yml, docker-compose-chat-blue-prod.yml, docker-compose-chat-deps-prod.yml, docker-compose-chat-green-prod.yml
=> [deploy] #194 - chat 서버 무중단배포 환경 구축

chat-server/src/main/java/com/napzak/chat/domain/chat/api/dto/response/ChatRoomSummary.java, core-domain/src/main/java/com/napzak/domain/chat/crud/chatmessage/ChatMessageRetriever.java, core-domain/src/main/java/com/napzak/domain/chat/vo/ChatMessage.java
=> [fix] #203 - LocalDateTime 설정으로 500 리턴 제한
